## Read CSV data using Pandas

In [18]:
import pandas as pd

In [19]:
orders_columns = [
    'order_id', 'order_date', 'order_customer_id', 'order_status'
]

In [20]:
orders_data_path = '../../../resources/data/retail_db/orders/part-00000'

pd.read_csv(orders_data_path).head()

   1  2013-07-25 00:00:00.0  11599           CLOSED
0  2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
1  3  2013-07-25 00:00:00.0  12111         COMPLETE
2  4  2013-07-25 00:00:00.0   8827           CLOSED
3  5  2013-07-25 00:00:00.0  11318         COMPLETE
4  6  2013-07-25 00:00:00.0   7130         COMPLETE

In [21]:
pd.read_csv(orders_data_path, header=None).head()

   0                      1      2                3
0  1  2013-07-25 00:00:00.0  11599           CLOSED
1  2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
2  3  2013-07-25 00:00:00.0  12111         COMPLETE
3  4  2013-07-25 00:00:00.0   8827           CLOSED
4  5  2013-07-25 00:00:00.0  11318         COMPLETE

Add columns name

In [22]:
pd.read_csv(
    orders_data_path,
    names=orders_columns
).head()

   order_id             order_date  order_customer_id     order_status
0         1  2013-07-25 00:00:00.0              11599           CLOSED
1         2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2         3  2013-07-25 00:00:00.0              12111         COMPLETE
3         4  2013-07-25 00:00:00.0               8827           CLOSED
4         5  2013-07-25 00:00:00.0              11318         COMPLETE

## Query example

In [24]:
orders = pd.read_csv(orders_data_path, names=orders_columns)

orders.head()

   order_id             order_date  order_customer_id     order_status
0         1  2013-07-25 00:00:00.0              11599           CLOSED
1         2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2         3  2013-07-25 00:00:00.0              12111         COMPLETE
3         4  2013-07-25 00:00:00.0               8827           CLOSED
4         5  2013-07-25 00:00:00.0              11318         COMPLETE

In [25]:
orders.columns

Index(['order_id', 'order_date', 'order_customer_id', 'order_status'], dtype='str')

In [30]:
orders['order_status'].unique()

<StringArray>
[         'CLOSED', 'PENDING_PAYMENT',        'COMPLETE',      'PROCESSING',
  'PAYMENT_REVIEW',         'PENDING',         'ON_HOLD',        'CANCELED',
 'SUSPECTED_FRAUD']
Length: 9, dtype: str

In [31]:
orders.query('order_status == "COMPLETE"')

       order_id             order_date  order_customer_id order_status
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
6             7  2013-07-25 00:00:00.0               4530     COMPLETE
14           15  2013-07-25 00:00:00.0               2568     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[22899 rows x 4 columns]

In [34]:
orders.query('order_status == "COMPLETE" and order_date == "2014-01-01 00:00:00.0" ').head()

       order_id             order_date  order_customer_id order_status
25881     25882  2014-01-01 00:00:00.0               4598     COMPLETE
25887     25888  2014-01-01 00:00:00.0               6735     COMPLETE
25888     25889  2014-01-01 00:00:00.0              10045     COMPLETE
25894     25895  2014-01-01 00:00:00.0               1044     COMPLETE
25896     25897  2014-01-01 00:00:00.0               6405     COMPLETE

In [33]:
orders.query('order_status == "COMPLETE" or order_status == "CLOSED" ')

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]

In [35]:
orders.query('order_status == ("COMPLETE" , "CLOSED") ')

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]