## Write CSV Data from File to Database Table

In [2]:
%load_ext sql

In [3]:
%env DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

env: DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

In [4]:
%%sql

TRUNCATE TABLE orders

Done.

[]

In [5]:
import pandas as pd

In [6]:
def get_column_name(schemas, ds_name, sorting_key='column_position'):
    column_details = schemas[ds_name]
    columns = sorted(column_details, key=lambda col: col[sorting_key])
    return [col['column_name'] for col in columns]

In [7]:
import json

In [10]:
schemas = json.load(open('../../../resources/data/retail_db/schemas.json'))

In [11]:
columns = get_column_name(schemas, 'orders')

In [12]:
df = pd.read_csv(
    '../../../resources/data/retail_db/orders/part-00000',
    names=columns
)

In [13]:
df

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [14]:
conn_uri = 'postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db'

In [ ]:
df.to_sql(
    'orders',
    conn_uri,
    if_exists='replace',
    index=False
)

883

In [20]:
pd.read_sql('orders', conn_uri)

       order_id order_date  order_customer_id     order_status
0             1 2013-07-25              11599           CLOSED
1             2 2013-07-25                256  PENDING_PAYMENT
2             3 2013-07-25              12111         COMPLETE
3             4 2013-07-25               8827           CLOSED
4             5 2013-07-25              11318         COMPLETE
...         ...        ...                ...              ...
68878     68879 2014-07-09                778         COMPLETE
68879     68880 2014-07-13               1117         COMPLETE
68880     68881 2014-07-19               2518  PENDING_PAYMENT
68881     68882 2014-07-22              10000          ON_HOLD
68882     68883 2014-07-23               5533         COMPLETE

[68883 rows x 4 columns]

## Write CSV Data from File to Database Table in Chunks

In [35]:
df_reader = pd.read_csv(
    '../../../resources/data/retail_db/orders/part-00000',
    names=columns,
    chunksize=10000
)

In [29]:
type(df_reader)

pandas.io.parsers.readers.TextFileReader

In [30]:
df_list = list(df_reader)

In [32]:
df_list[0]
# 10,000 rows = chunksize

      order_id             order_date  order_customer_id     order_status
0            1  2013-07-25 00:00:00.0              11599           CLOSED
1            2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2            3  2013-07-25 00:00:00.0              12111         COMPLETE
3            4  2013-07-25 00:00:00.0               8827           CLOSED
4            5  2013-07-25 00:00:00.0              11318         COMPLETE
...        ...                    ...                ...              ...
9995      9996  2013-09-25 00:00:00.0              11839          PENDING
9996      9997  2013-09-25 00:00:00.0               3471  PENDING_PAYMENT
9997      9998  2013-09-25 00:00:00.0               9419          PENDING
9998      9999  2013-09-25 00:00:00.0               1185           CLOSED
9999     10000  2013-09-25 00:00:00.0               8983       PROCESSING

[10000 rows x 4 columns]

In [36]:
for idx, df in enumerate(df_reader):
    print(f'Size of chunk {idx} is {df.shape}')

Size of chunk 0 is (10000, 4)
Size of chunk 1 is (10000, 4)
Size of chunk 2 is (10000, 4)
Size of chunk 3 is (10000, 4)
Size of chunk 4 is (10000, 4)
Size of chunk 5 is (10000, 4)
Size of chunk 6 is (8883, 4)

In [41]:
for idx, df in enumerate(df_reader):
    print(f'Size of chunk {idx} is {df.shape}')
    df.to_sql(
        'orders',
        conn_uri,
        if_exists='append',
        index=False
    )

In [42]:
ds_name = 'orders'
pd.read_sql(ds_name, conn_uri)

       order_id order_date  order_customer_id     order_status
0             1 2013-07-25              11599           CLOSED
1             2 2013-07-25                256  PENDING_PAYMENT
2             3 2013-07-25              12111         COMPLETE
3             4 2013-07-25               8827           CLOSED
4             5 2013-07-25              11318         COMPLETE
...         ...        ...                ...              ...
68878     68879 2014-07-09                778         COMPLETE
68879     68880 2014-07-13               1117         COMPLETE
68880     68881 2014-07-19               2518  PENDING_PAYMENT
68881     68882 2014-07-22              10000          ON_HOLD
68882     68883 2014-07-23               5533         COMPLETE

[68883 rows x 4 columns]